apiVersion: v1
kind: Service
metadata:
  name: ecommerce-srv
spec: 
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - name: ecommerce
      protocol: TCP  
      port: 3000
      targetPort: 3000